### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by shyim** [meilisearch/meilisearch-php#105]
- meilisearch/meilisearch-php v0.12.0 requires php ^7.2 -> your php version (8.0.0beta1) does not satisfy that requirement.

**Comment by curquiza** [comment]
Hello @shyim!

If I'm not wrong php8 is still in beta, so we will not support php8 until the release is out 🙂

**Comment by shyim** [comment]
Its already at rc1. Final release is scheduled for end next month

**Comment by curquiza** [comment]
We will wait until the end of November then 😉 As it's possible, we would rather not include unstable dependencies and requirements in this package.

**Comment by Raymonf** [comment]
In that case, wouldn't it be better to just use `>=7.2`? FWIW, PHP RCs are more or less finalized when it comes to features.

**Comment by curquiza** [comment]
Feel free to open a draft PR that fixes this issue if you wish, but it will not be merged before the official major version is out (November 26th if I'm not wrong) 🙂 We cannot depend on a release candidate version for the moment since MeiliSearch is not stable so our SDK is not either 😉

**Comment by eskombro** [comment]
Totally agree with @curquiza, if RCs in PHP are quite stable in PHP, you can start testing them in a branch so when it is officially released, all the work is ready to be merged. But until there is no official release, MeiliSearch clients shouldn't rely on them 👍

**Comment by szainmehdi** [comment]
I've opened a PR for this (#116). I don't see any reason to hold off on merging that before PHP 8.0 is stable. There are no breaking changes, and no PHP 8.0 specific dependencies are introduced. PHP 7.2+ compatibility is preserved.

**Comment by curquiza** [comment]
Hello @szainmehdi!
Since it seems to be important for some of you, I can reconsider our position and I will check your work 🙂
If there is any issue related to PHP 8 in this package after the merge of this PR, you have to be aware the Meili team cannot afford to spend time fixing this issue until PHP 8 is officially stable. Of course, the external contribution would be more than welcome in this case! I just want to be transparent with you 🙂
Thanks again for your PR! It seems really clear!
