### ISSUE TITLE
Replace Guzzle with PSR Interface

### ISSUE THREAD

**Issue by Zeichen32** [meilisearch/meilisearch-php#11]
The current implementation is fixed to use Guzzle as http client. But most frameworks already have a build in psr compatible http client.  (https://www.php-fig.org/blog/2018/11/psr-18-the-php-standard-for-http-clients/)

I think it would be a good practise to let the developer choose the used http client.
If it is okay, i would like to create a PR with the necessary change to depend on the psr http client interface instead of guzzle.

**Comment by curquiza** [comment]
Hey!
Thanks for this remark! And yes, feel free to do a PR! 🙂
We really appreciate this kind of contribution.

**Comment by curquiza** [comment]
@Zeichen32, I see you started a PR for this issue, thanks a lot! 🙂

I have some questions about that (I found out this possibility of choosing the HTTP Client in PHP).

Are you currently implementing an HTTP client so that this SDK will provide a default one? 
Indeed, my main worry is about simplicity: will the package still be as easy to use for a newcomer using no web framework? I mean, I want a new user to copy/paste the getting started example of code, and to see that everything works without any configuration 🙂

Thanks for your time answering my naive questions.
And thanks again for the huge and useful work you are doing on this SDK 😀

**Comment by Zeichen32** [comment]
@curquiza  This was the main reason because the PR is in WIP stage. 

The current implementation does not provide a default client.
I know this is not very straightforward, so we need to update the docs with the necessary composer commands.

The other way would to be provide a default Client and just mention in the docs the ability to change the client.

Both ways are okay for me, i just need your opinion to finish the PR.

**Comment by curquiza** [comment]
@Zeichen32 thanks for your clarification 🙂

To be honest, the team and I would keep our tool easy to use! That's why we would rather have the second option, I mean `providing a default Client and just mention in the docs the ability to change the client.`

With this option, the Getting Started section will not change, right? 
We will just need to add a part about how to change the default client if I understand correctly.

Isn't this option to complicated? 🙂 Thanks again for your work, I like the idea of giving the possibility to chose the client!

**Comment by Zeichen32** [comment]
No this not complicated to implement. We just need to add the composer dependencies for the default client. 

For Guzzle6 this dependencies are needed:
```
"guzzlehttp/psr7": "^1.6",
"guzzlehttp/guzzle": "~6.0",
"php-http/guzzle6-adapter": "^2.0",
"http-interop/http-factory-guzzle": "^1.0"
````
Currently i have added these dependencies only for the dev/test environment. I will update and rebase the PR tomorrow.
