### ISSUE TITLE
Discussion the drop support of PHP v7.3

### ISSUE THREAD

**Issue by 94noni** [meilisearch/meilisearch-php#179]
Hi,

I began using MeiliSearch recently, and with PHP for a personal project

Regarding:

- https://www.php.net/supported-versions.php
- https://packagist.org/packages/meilisearch/meilisearch-php/php-stats#0.18

I am opening this issue to discuss the minimum version of this package, I think requiring PHP v7.4 could improve the codebase for the better, and will be very happy to contribute to :)

Feel free to close, related to https://github.com/meilisearch/meilisearch-php/issues/136 and https://github.com/meilisearch/meilisearch-php/issues/165

Cheers!

**Comment by alallema** [comment]
Hi @94noni,
Thank you for raising this issue. Until now we keep the versions until they are no longer supported (end of 2021 for 7.3), we don't want to rush people.
But it's a very relevant question and I'd be glad to have some opinions from the community about it. So don't hesitate to comment, I let this issue open.

**Comment by codedge** [comment]
There is now a nice live PHP version stats view: https://packagist.org/php-statistics

So currently

* 20% still run on 7.3.
* 65% run on 7.4 & 8.0.

> we don't want to rush people.

That is a good one 😄 .. but I get your point. 

I think 6th Dec 2021 when 7.3 security support ends there can be a hard cut dropping 7.3. People then had 1 year of _no rushing_ since the active support stopped for 7.3 😉 

And the good thing is that people who still wants to use this lib with php 7.3 they still can. It is just that they probably won't benefit from future additions to this lib. And this is one major point where I can understand to adopt new versions earliert and drop old ones. There is no downside for the people. And if there is a major bug upcoming you can still think about backporting the fix.

**Comment by esmultivac** [comment]
I think the current policy is a good one. No doubt that the code can be smaller and more polished dropping support for not so old versions, but it can be hard for some projects to move on to the newer ones. We're currently working on upgrading from 7.2 to 8.0 and it's a ton of work. It's a work that must be done eventually, of course, and the end of support is a very good milestone to force it.
