### ISSUE TITLE
For getDocuments **attributesToRetrieve** param works only if is string type.

### ISSUE THREAD

**Issue by vitalijm** [meilisearch/meilisearch-php#288]
**Describe the bug**
For getDocuments **attributesToRetrieve** param works only if is string type.
If array type, then throwing error:

**Fatal error: Uncaught MeiliSearch ApiException: Http Status: 400 - Message: Query deserialize error: unknown field `attributesToRetrieve[0]`, expected one of `offset`, `limit`, `attributesToRetrieve` - Code: bad_request - Type: invalid_request - Link: https://docs.meilisearch.com/errors#bad_request thrown in /app/vendor/meilisearch/meilisearch-php/src/Http/Client.php on line 215**

**To Reproduce**
1.
PHP:
`$hits = $client->index('movies')->getDocuments(['limit' => 2, 'offset' => '2', 'attributesToRetrieve' => ['title','poster']]);`
`print_r($hits);`
2. See error

**MeiliSearch version:** [v0.25.0]

**Additional context**
https://github.com/meilisearch/meilisearch-php
OS: debian 11, via docker

**Comment by alallema** [comment]
Hi @vitalijm,
Thanks for raising this issue!
The `getDocument` method is a `GET` `HTTP` method so the parameters are sent by the `URL`. You can actually send it that way if you want to send multiple parameters:
```
$hits = $client->index('movies')->getDocuments(['limit' => 2, 'offset' => '2', 'attributesToRetrieve' => 'title,poster']);
```
At the moment, this method is not intended to take `Arrays` because the `API` takes `String`.
This could be confusing because the `attributesToRetrieve` in the search parameter could be an "array".
I will open an issue about it on the `integration` repository to ask the team's opinion.

**Comment by vitalijm** [comment]
Hi! Thanks ;)

**Comment by alallema** [comment]
I'm closing this issue due to the opening of this [one](https://github.com/meilisearch/integration-guides/issues/167).
