### ISSUE TITLE
Get errors and google can't find nothing

### ISSUE THREAD

**Issue by erikobox** [meilisearch/meilisearch-php#352]
PHP version: 7.4

Very bad documentation you have. I installed everything as written but this is bad product and not working as described in your website.

addDocuments() is working fine
getTask() is working fine

search() throwing fatal error

Notice: Undefined index: estimatedTotalHits in /var/www/www-root/data/www/*******.com/vendor/meilisearch/meilisearch-php/src/Search/SearchResult.php on line 47

Fatal error: Uncaught TypeError: Typed property MeiliSearch\Search\SearchResult::$estimatedTotalHits must be int, null used in /var/www/www-root/data/www/*******.com/vendor/meilisearch/meilisearch-php/src/Search/SearchResult.php:47 Stack trace: #0 /var/www/www-root/data/www/*******.com/vendor/meilisearch/meilisearch-php/src/Endpoints/Indexes.php(193): MeiliSearch\Search\SearchResult->__construct() #1 /var/www/www-root/data/www/*******.com/search.php(34): MeiliSearch\Endpoints\Indexes->search() #2 {main} thrown in /var/www/www-root/data/www/*******.com/vendor/meilisearch/meilisearch-php/src/Search/SearchResult.php on line 47

**Comment by brunoocasali** [comment]
Hi, @erikobox can you tell me what is your Meilisearch engine version?

**Comment by erikobox** [comment]
Hi @brunoocasali [brunoocasali](https://github.com/brunoocasali), version 0.27.1 on Debian 10. from DigitalOcean marketplace.

**Comment by brunoocasali** [comment]
I’m sorry you have this feeling, we are really open to feedback. If you have any suggestions, please open an issue explaining clearly what could be improved in the [documentation repository](https://github.com/meilisearch/documentation).

Can you be a little bit more precise about why it’s a bad product?
Same as for the documentation we are really open to feedback, you can open [discussion on our product repository](https://github.com/meilisearch/product/discussions) so that the product team can consider your needs. It would be really helpful.

We keep a section in our [README](https://github.com/meilisearch/meilisearch-php#-compatibility-with-meilisearch) that says we only support v0.28.0 of the search engine.
So if you want to use `Meilisearch engine v0.27` you should go back to the [PHP v0.23.3](https://github.com/meilisearch/meilisearch-php/tree/v0.23.3#-compatibility-with-meilisearch) 😃 

Again, I understand your frustration, but be sure we are doing our best by working hard on providing an amazing product, documentation, and search experience. It could happen sometimes we have failures, I’m sure you can understand.
Plus our code is open source, like our product, meaning every contribution is accepted, so if you have any ideas or suggestions to make it better, you are more than welcome!

Have a nice day!

**Comment by erikobox** [comment]
@[brunoocasali](https://github.com/brunoocasali) thank you for reply, I hope this will help someone who got same error. HTML, CSS, JQuery, PHP, MySQL is the best technology for building web. I don't get it, why nowadays devs making things so hard to use.
