### ISSUE TITLE
allRaw() Indexes not using $options array.

### ISSUE THREAD

**Issue by Jared87** [meilisearch/meilisearch-php#359]
**Description**
The allRaw() function in src/Endpoints/Indexes.php on line 98 is not using the $option array, so the offset and limiting were not applied.

**Expected behavior**
Limiting and offset are working.

**Current behavior**
It ignores the offset and uses 20 as limit.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/6816946/181240010-914bbb6b-bd4a-437a-9c62-8325cab64b14.png)

**Environment (please complete the following information):**
- OS: Ubuntu
- Meilisearch version: [e.g. v.0.28.1]
- meilisearch-php version: [e.g v0.24.0]

**Comment by brunoocasali** [comment]
Hi @Jared87, thanks for contributing with Meilisearch!

Indeed it was a missing piece!
But I would like to advise you not to use this method if possible because this is an "open door" to Meilisearch, so in the future if Meilisearch changes anything in their response, we may not be able to handle the breaking changes for you.

**Comment by Jared87** [comment]
Thank you for the quick response and the advice! 
We stumbled over this during an update and it was a approach to check if an index is already created. I'll going to refactor this.
