### ISSUE TITLE
Class "MeiliSearch\MeiliSearch" not found

### ISSUE THREAD

**Issue by francoism90** [meilisearch/meilisearch-php#440]
**Description**
```php artisan scout:import <model-class>```

```
"laravel/scout": "^9.7",
"meilisearch/meilisearch-php": "^0.26.1",
```

**Expected behavior**
Use `Meilisearch\Meilisearch` on Laravel Scout

**Current behavior**
Uses wrong class.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Linux
- Meilisearch version: latest
- meilisearch-php version: 0.26.1

**Comment by brunoocasali** [comment]
Hi @francoism90.

I released a new version v0.27.0, where you can use the correct class names, the change was intentional, but the breaking was not.

You can check this links for more info https://github.com/meilisearch/meilisearch-php/pull/441, https://github.com/meilisearch/meilisearch-php/pull/431
