### ISSUE TITLE
Call to undefined method Meilisearch\Client::deleteAllIndexes()

### ISSUE THREAD

**Issue by oleaass** [meilisearch/meilisearch-php#485]
When attempting to execute `php artisan scout:delete-all-indexes` we get this error.

![image](https://user-images.githubusercontent.com/46921124/228810388-4992dedd-5b87-456b-9074-9a361d19cf81.png)

**Comment by brunoocasali** [comment]
Hi @oleaass, this command was removed from this library because it was not correctly implemented.

It was also introduced as part of the laravel/scout here https://github.com/laravel/scout/pull/678.
Please ensure you're using Laravel Scout v10 + Meilisearch PHP v1.0 or newer. To solve the issue :)

I'll take a look in your PR when I come back of my holidays :)

**Comment by oleaass** [comment]
Hi @brunoocasali, thanks for replying :)

You are correct. We using laravel/scout:9.6 with Meilisearch 1.0.

Enjoy your holiday!

**Comment by brunoocasali** [comment]
I'll close this because Meilisearch engine will probably support this feature in the future.

If someone wants it now feel free to reopen and work on it!
