### ISSUE TITLE
/multi-search endpoint 404 Not Found

### ISSUE THREAD

**Issue by vanrijs** [meilisearch/meilisearch-php#504]
All,

Im running the latest version (1.1) and got an error on the /multi-search endpoint: 404 Not Found. 

This is my CURL command:
```
curl --location 'http://localhost:7700/multi-search' \
--header 'Content-Type: application/json' \
--data '{
    "queries": [
        {
            "indexUid": "orders_index",
            "q": "test"
        }
    ]
}'
```

Endpoints like /search and /indexes works well. 

Any ideas? 

Raymond

Edit1: tried to setup Meilisearch Cloud. The multi-search endpoint works well there. 
In my terminal I see package version 0.29.1 on meilisearch --version

Edit2: in the end Meilisearch will get hosted on DigitalOcean, I'll try the version there too this weekend.

**Comment by brunoocasali** [comment]
You must have the latest meilisearch version. The `/multi-search` route was introduced in Meilisearch engine v1.1.

`In my terminal, I see package version 0.29.1 on meilisearch --version`. That's why you're getting your error. You need to have a compatible meilisearch version.

As stated here: https://github.com/meilisearch/meilisearch-php/releases/tag/v1.1.0

If you want to adopt new features of this release, **update the Meilisearch server** to the according version.
