### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by sanderbaas** [meilisearch/meilisearch-php#76]
I am trying to install `meilisearch-laravel-scout` in my project. This project is using Guzzle 7 because of other dependencies. If I understand it correctly the option in `meilisearch-php` exists to use another HTTP Client, but this other HTTP Client can not be Guzzle 7. Reason being that the Guzzle 7 requirement conflicts with the `php-http/guzzle6-adapter` requirement for Guzzle 6.

Is there a way to use meilisearch-php with Guzzle 7?

**Comment by curquiza** [comment]
Hello @sanderbaas!
Sorry for the delay!

I'm not sure to really understand. Did you succeed to install meilisearch-laravel-scout?

If it's possible, can you send the `composer.json` file? 🙂

**Comment by sanderbaas** [comment]
I was not able to install meilisearch-laravel-scout, because meilisearch-php requires a version of Guzzle that collides with other dependencies in my project. I trimmed my composer.json a bit, see below. With this installed there is no installable set of packages when performing: `composer require meilisearch/meilisearch-laravel-scout`

My composer.json
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.0",
        "aws/aws-sdk-php": "~3.0",
        "laravel/framework": "^7.0"
    },
    "require-dev": {
    },
    "autoload": {
        "classmap": [
        ],
        "psr-4": {
        },
        "files": [
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by ppshobi** [comment]
I don't think you can use it with guzzle 7 right now, Because of our current locked in dependency with `guzzle6-adapter`, and guzzle 6 adapter can't be used with guzzle 7. We will have to update the source code to support guzzle 7. Would you mind @sanderbaas to send a PR? We could try to approve/review it and release a version quicker.

**Comment by ppshobi** [comment]
To explain a bit more

`guzzlehttp/guzzle` provides PSR-18 factories, and `http-interop/http-factory-guzzle` provides PSR-17 factories, both of them using `guzzlehttp/psr7` for the PSR-7 implementation. In the future `guzzlehttp/psr7` will likely get the PSR-17 factories built-in to it, but for now, it doesn't have that, so you need that additional interop package.

https://github.com/GrahamCampbell/Laravel-GitHub/issues/113

You can refer here for a better understanding of how [ Digital Ocean Laravel ](https://github.com/GrahamCampbell/Laravel-GitHub/compare/9.3...10.0) is trying to support guzzle 7, look into the composer.json maybe. I guess you could try a PR. Thanks

**Comment by curquiza** [comment]
Ok I understand better @sanderbaas! And thanks for the explanations @ppshobi!

Indeed, it would be perfect if we could solve this issue 🙂 As @ppshobi said, feel free to open a PR if you are interested to contribute to this open-source project! It would be a pleasure to guide you if needed!

**Comment by pelletiermaxime** [comment]
Just my 2 cents, but I would remove the direct guzzle dependency and just document that you need a psr18 client like symfony/http-client or guzzle6-adapter or guzzle7 and maybe add suggest section in your composer.json.

**Comment by ppshobi** [comment]
Yes, indeed.

**Comment by ppshobi** [comment]
https://github.com/meilisearch/meilisearch-php/pull/81

**Comment by curquiza** [comment]
Hello @ppshobi !
I saw your PR (#81), thanks for your work! And sorry for the delay!

This kind of SDK design decision is not that easy for us (the MeiliSearch integration team). Indeed, our priority is to make tools **really easy to use**: the less there are steps to run and try MeiliSearch and its tool, the better it is!

See the [Algolia PHP client](https://github.com/algolia/algoliasearch-client-php#-getting-started) and the [Elastic PHP client](https://github.com/elastic/elasticsearch-php#installation-via-composer). There is no additional client to install with Composer.

About Algolia PHP client, if I understand well, they have implemented their own HTTP client with these dependencies:
- psr/http-message: ^1.0
- psr/log: ^1.0
- psr/simple-cache: ^1.0
[See it on Packagist](https://packagist.org/packages/algolia/algoliasearch-client-php).
And they suggest using guzzle if you don't want to use their own HTTP client, see [these lines](https://github.com/algolia/algoliasearch-client-php/blob/889a631b15b1115458fa6e974267bc5fa1bb05c4/composer.json#L42-L44).

As MeiliSearch is really similar to Algolia, could we be strongly inspired by Algolia to integrate the same HTTP client to our SDK instead of enforcing our user to download an additional package (an HTTP client) with MeiliSearch PHP? 🙂 What do you think?
Of course, we would keep the possibility to change the default HTTP client!

**Comment by ppshobi** [comment]
Yes, it should be easy to use meilisearch-sdk, but the problem currently is we are dependent on guzzle 6, which prevents the users from installing other http clients for example guzzle-7, and probably will prevent any other package to be installed with a dependency of guzzle 7, Because we locked our dependency on Guzzle 6.  

Elastic has their own direct CURL implementation. and algolia has something similar and they don't prevent us from installing guzzle 7 or any other http clients. Unfortunately, we do.

I don't know exactly how the algolia team implemented their solution, but if someone can shed a light on it, it would be great as well. Even I don't like having to go through the documentation again to install a package. **Also the PR is still in draft mode for the same reason.**

Writing our own http client probably will be reinventing the wheel in these days of psr interfaces and plenty of clients dependent on it. We just need to make sure our package works with other clients by depending on the interface. The PR is not yet final. But the current way mentioned in the PR to install the sdk is adopted by many packages.

1. https://github.com/GrahamCampbell/Laravel-DigitalOcean
2. https://github.com/GitLabPHP/Client
3. https://github.com/KnpLabs/php-github-api
.

**Comment by curquiza** [comment]
Thanks @ppshobi for your detailed answer and your examples.
Thanks to the README examples your provide I realize I might have over-estimated the complexity that this change brings in the README.

I thought the users should add the guzzle package during the import AND add more lines of code compared to the current way using meilisearch-php.

Could you confirm:
- the [`Getting Starting`](https://github.com/meilisearch/meilisearch-php#-getting-started) section will not change at all? Only the [`Installation`](https://github.com/meilisearch/meilisearch-php#-installation) section should change.
- the [`Replace HTTP client`](https://github.com/meilisearch/meilisearch-php#-replace-http-client) will not change? If it will indeed change, it's not a problem, but don't forget to change the README in your PR 🙂

If there is indeed no change in the Getting Starting except the import, we are ok to accept this change as it removes dependencies issues.

**Comment by ppshobi** [comment]
Yes. as of now only the installation section will change. And the replacing the client part will not/should not be required. Since our sdk will automatically discover which http client is installed and use it automatically. (that part is written here https://github.com/meilisearch/meilisearch-php/blob/bad854e969a1bd9962262766f6d8e2156c17a0e7/src/Http/Client.php#L57).

But since we have a dependency of guzzle6 adapter, the package discovers it and use it

**Comment by curquiza** [comment]
> Since our sdk will automatically discover which http client is installed and use it automatically. 

Of course! Makes sense 😅

Let's start it then! You can pass the PR as ready for review when you are ready 🙂

**Comment by shokme** [comment]
@ppshobi 

While reviewing a PR for scout, for guzzle 7 you still have to provide the guzzle instance.

```php
        resolve(EngineManager::class)->extend('meilisearch', function () {
            return new MeilisearchEngine(
                new Client(config('meilisearch.host'), config('meilisearch.key'), new \GuzzleHttp\Client()),
                config('scout.soft_delete', false)
            );
        });
```

And obviously it will break all version that are not using guzzle **7**.
But I found a solution while browsing the web: https://github.com/php-http/discovery/pull/175/files
instead of `HttpClientDiscovery::find()` we should use `Psr18ClientDiscovery::find()` (looks like it also work with guzzle6-adapter)

It will not work with non psr-18 client, so we should keep HttpClientDiscovery, by using condition we should be able to have everything working, what do you think ?

**Comment by bensherred** [comment]
Just to confirm @shokme are you suggesting that [here](https://github.com/ppshobi/meilisearch-php/blob/e73d3eb4118a512203ae3f015895a85c83b56c36/src/Http/Client.php#L56), we should do something like:

```php
$this->http = $httpClient ?: (Psr18ClientDiscovery::find() ?? HttpClientDiscovery::find());
```

**Comment by shokme** [comment]
Yes ! thank you for mentioning it ^^
But your suggestion can't work, because of the exception thrown by the find method. (you can try by reversing psr18 and http)

I will also start searching for a way to do it :smile: thank you for trying and helping us ! very appreciate :+1:

**Comment by ppshobi** [comment]
1. I still don't know why guzzle 7 is not being discovered by our http client discovery call here https://github.com/meilisearch/meilisearch-php/blob/ab9d40c81561caabef890698f31c0b6e0db5727c/src/Http/Client.php#L56

2. Specifying a condition for just to support guzzle 7 is something not very desirable
3. There is [guzzle7-adapter ](https://github.com/php-http/guzzle7-adapter)now, Maybe we could try to make it work with guzzle7 and our sdk

**Comment by ppshobi** [comment]
Ideally the replacing client part needs to be removed. our sdk should automatically discover whatever compatible client is installed. But this is happening for other clients guzzle 7 is not working

**Comment by ppshobi** [comment]
Or there is something, that I totally miss on this whole PSR 17,18 drama :)

**Comment by shokme** [comment]
>     1. I still don't know why guzzle 7 is not being discovered by our http client discovery call here

Because it's not reference inside the `HttpClient::class` but inside `Psr18Client::class`

When you call `HttpClientDiscovery::find()`

```php
    public static function find()
    {
        try {
            $client = static::findOneByType(HttpClient::class);
        } catch (DiscoveryFailedException $e) {
            throw new NotFoundException('No HTTPlug clients found. Make sure to install a package providing "php-http/client-implementation". Example: "php-http/guzzle6-adapter".', 0, $e);
        }

        return static::instantiateClass($client);
    }
```

where `HttpClient::class` is the parameter given to

```php
    public static function getCandidates($type)
    {
        if (Psr18Client::class === $type) {
            return self::getPsr18Candidates();
        }

        return self::$classes[$type] ?? [];
    }
```

So when you use Psr18 you enter in the condition `Psr18Client::class === $type` where Psr18Client is an alias of `Psr\Http\Client\ClientInterface`

**Comment by shokme** [comment]
Ok after check we should just replace `HttpClientDiscovery::find();` by `Psr18ClientDiscovery::find()`.
I have tested all client:
kriswallsmith/buzz, php-http/curl-client, symfony/http-client with nyholm/psr7
guzzle6-adapter,guzzle7 with http-interop/http-factory-guzzle

All of them are working. Looks like all the client above are implementing the PSR-18 (I still have to check)

If someone can also try this is working, to be sure I don't fail somewhere ^^'

**Comment by curquiza** [comment]
@shokme, thanks for your investigation! Can you open a PR? I will check 👍

**Comment by ppshobi** [comment]
Wonderful. Let's see the pr

**Comment by curquiza** [comment]
Hope I can definitely close this issue thanks to:
- #81
- #85  
- #88

The [v0.14.1](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.14.1) is now released!

Thanks to all of you guys! 🎉
